name: 'Submodules Sync'

on:
  # Allows you to run this workflow manually from the Actions tab or through HTTP API
  workflow_dispatch:

jobs:
  sync:
    name: 'Submodules Sync'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    # Update references
    - name: Git Sumbodule Update
      run: |
        git pull --recurse-submodules
        git submodule update --remote --recursive

    - name: Add the submodules in case they are not already added
      run: |
        sed '/url = /!d; s/^\s*url = \([^ ]*\) */git submodule add \1/' .gitmodules | tee allsubmodules | sh
        cat allsubmodules
        rm allsubmodules
      
    - name: Commit update
      run: |
        git config --global user.name 'Git bot'
        git config --global user.email 'bot@noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        if [ "$(git status --porcelain --untracked-files=no | wc -l)" = "0" ]; then echo "No changes to commit"; else git commit --amend -a --no-edit && git push -f; fi
